jobs:
- name: repave
  serial: true
  plan:
  - put: lock
    params: {acquire: true}
  - get: bosh-repave-repo
    trigger: false
  - get: scheduler
    trigger: true
  - task: repave
    file: bosh-repave-repo/ci/tasks/repave/task.yml
    params:
      SKIP_SSL_VALIDATION: {{skip-ssl-validation}}
      OPSMAN_URL: {{opsman-url}}
      OPSMAN_USERNAME: {{opsman-username}}
      OPSMAN_PASSWORD: {{opsman-password}}
      OPSMAN_CLIENT_ID: {{opsman_client_id}}
      OPSMAN_CLIENT_SECRET: {{opsman_client_secret}}
      DEPLOYMENTS: {{deployments}}
      JOBS: {{jobs}}
      REPAVE_SINGLETON_JOBS: {{repave-singleton-jobs}}
      PERFORM_DRY_RUN_ONLY: {{perform-dry-run-only}}
    ensure:
      put: lock
      params:
        release: lock

resources:
- name: bosh-repave-repo
  type: git
  source:
    uri: git@github.com:J4U-Nimbus/bosh-repave.git
    branch: master
    private_key: {{git_private_key}}
- name: scheduler
  type: time
  source:
    start: {{scheduler-time-window-start}}
    stop: {{scheduler-time-window-stop}}
    location: {{scheduler-time-location}}
- name: lock
  type: pool
  source:
    uri: {{lock-git-repo-uri}}
    branch: {{lock-git-repo-branch}}
    pool: {{lock-pool-name}}
    private_key: {{lock-git-private-key}}
